name: code_gate
on: [push, pull_request]
jobs:
  test-gate:
    name: Run code analysis
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          export CI=true
          /bin/bash tests/run-all.sh
      - run: echo "Job's status is ${{ job.status }}."
